name: Test Binaries

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Hash (Optional)
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  builtin:
    name: ${{ matrix.os }}/${{ matrix.TARGET }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-13, macos-14, windows-2019, windows-2022]

        include:
        - os: ubuntu-20.04
          TARGET: "ubuntu2004-x86_64"
          SHORTOS: ubuntu
        - os: ubuntu-22.04
          TARGET: "ubuntu2204-x86_64"
          SHORTOS: ubuntu
        - os: macos-13
          TARGET: "darwin-x86_64"
          SHORTOS: osx
        - os: macos-14
          TARGET: "darwin-aarch64"
          SHORTOS: osx
        - os: windows-2019
          TARGET: "windows-x86_64"
          SHORTOS: win
        - os: windows-2022
          TARGET: "windows-x86_64"
          SHORTOS: win

    steps:
      - name: Checkout IDAES-ext source
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Configure curl
        run: |
          CURLRC="$(cat <<EOF
             retry = 0
             max-time = 30
          EOF
          )"
          echo "$CURLRC" > ${GITHUB_WORKSPACE}/.curlrc
          echo "$CURLRC" > ${GITHUB_WORKSPACE}/_curlrc
          echo "CURL_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Setup IDAES package directories
        run: |
          IDAES_DIR="${GITHUB_WORKSPACE}/cache/tpl"
          mkdir -p "$IDAES_DIR"
          DOWNLOAD_DIR="${GITHUB_WORKSPACE}/cache/download"
          mkdir -p "$DOWNLOAD_DIR"
          echo "IDAES_DIR=$IDAES_DIR" >> $GITHUB_ENV
          echo "DOWNLOAD_DIR=$DOWNLOAD_DIR" >> $GITHUB_ENV
      - name: Install Dependencies
        run: |
          pip install pyomo pytest scipy "numpy<2" parameterized
      - name: Download Binaries
        run: |
            IPOPT_DIR=$IDAES_DIR/bin
            echo "$IPOPT_DIR" >> $GITHUB_PATH
            echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$IPOPT_DIR" >> $GITHUB_ENV
            mkdir -p $IPOPT_DIR
            IPOPT_TAR=${DOWNLOAD_DIR}/ipopt.tar.gz
            if test ! -e $IPOPT_TAR; then
                echo "...downloading Ipopt"
                URL=https://github.com/IDAES/idaes-ext
                RELEASE=$(curl --max-time 150 --retry 8 \
                    -L -s -H 'Accept: application/json' ${URL}/releases/latest)
                VER=$(echo $RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
                URL=${URL}/releases/download/$VER/idaes-solvers-${{ matrix.TARGET }}.tar.gz
                curl --max-time 150 --retry 8 \
                  -L $URL > $IPOPT_TAR
 
            fi
            cd $IPOPT_DIR
            if test "${{ matrix.SHORTOS }}" == osx; then
                tar -xvf $IPOPT_TAR
            else
                tar -xzi < $IPOPT_TAR
            fi
            echo ""
            echo "$IPOPT_DIR"
            ls -l $IPOPT_DIR
      - name: Configure and Install cyipopt
        run: |
          echo "TODO - patch needed"
      - name: Run tests
        run: |
          pytest -v -rs `pwd`/test

  docker:
    name: ${{ matrix.container }}/${{ matrix.TARGET }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container: ["redhat/ubi8", "redhat/ubi9", "debian:10", "debian:11", "debian:12"]
        include:
          - container: redhat/ubi8
            TARGET: "el8"
            SHORTOS: el
          - container: redhat/ubi9
            TARGET: "ubuntu2204"
            SHORTOS: el
          - container: "debian:10"
            TARGET: "ubuntu2204"
            SHORTOS: deb
          - container: "debian:11"
            TARGET: "ubuntu2004"
            SHORTOS: deb
          - container: "debian:12"
            TARGET: "ubuntu2204"
            SHORTOS: deb
    steps:
    - name: Check out source
      uses: actions/checkout@v4
    - name: Install basic libraries
      run: |
        cat /etc/*-release
        if test "${{ matrix.SHORTOS }}" == el; then
          yum -y install wget curl || yum -y install --allowerasing wget curl
        else
          apt-get update && apt-get -y install wget curl
        fi
        if [ `uname -m` = "aarch64" ]; then 
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh -O $WORKSPACE/miniconda.sh
          DISTRO='aarch64'
        fi
        if [ `uname -m` = "x86_64" ]; then
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $WORKSPACE/miniconda.sh
          DISTRO='x86_64'
        fi
        echo "DISTRO=$DISTRO" >> $GITHUB_ENV
        chmod +x $WORKSPACE/miniconda.sh
        bash $WORKSPACE/miniconda.sh -b -p $WORKSPACE/miniconda
        ls $WORKSPACE/miniconda/bin
    - name: Setup IDAES package directories
      run: |
        IDAES_DIR="${GITHUB_WORKSPACE}/cache/tpl"
        mkdir -p "$IDAES_DIR"
        DOWNLOAD_DIR="${GITHUB_WORKSPACE}/cache/download"
        mkdir -p "$DOWNLOAD_DIR"
        echo "IDAES_DIR=$IDAES_DIR" >> $GITHUB_ENV
        echo "DOWNLOAD_DIR=$DOWNLOAD_DIR" >> $GITHUB_ENV
    - name: Install Dependencies
      run: |
        eval "$(/miniconda/bin/conda shell.bash hook)"
        conda --version
        conda create -n idaes python=3.10 pip psutil
        conda activate idaes
        # Grab the most recent release of the IDAES extensions
        pip install pyomo pytest scipy "numpy<2" parameterized
    - name: Download Binaries
      run: |
          IPOPT_DIR=$IDAES_DIR/bin
          echo "$IPOPT_DIR" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$IPOPT_DIR" >> $GITHUB_ENV
          mkdir -p $IPOPT_DIR
          IPOPT_TAR=${DOWNLOAD_DIR}/ipopt.tar.gz
          if test ! -e $IPOPT_TAR; then
              echo "...downloading Ipopt"
              URL=https://github.com/IDAES/idaes-ext
              RELEASE=$(curl --max-time 150 --retry 8 \
                  -L -s -H 'Accept: application/json' ${URL}/releases/latest)
              VER=$(echo $RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
              URL=${URL}/releases/download/$VER/idaes-solvers-${{ matrix.TARGET }}-$DISTRO.tar.gz
              curl --max-time 150 --retry 8 \
                -L $URL > $IPOPT_TAR
          fi
          cd $IPOPT_DIR
          tar -xzi < $IPOPT_TAR
          echo ""
          echo "$IPOPT_DIR"
          ls -l $IPOPT_DIR
    - name: Configure and Install cyipopt
      run: |
        echo "TODO - patch needed"
    - name: Run tests
      run: |
        eval "$(/miniconda/bin/conda shell.bash hook)"
        conda activate idaes
        pytest -v -rs `pwd`/test
